from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Mapping

import numpy as np

from cooperative.message_transport import MessageChannel
from cooperative.recursive_cooperative_runner import (
    RecursiveCooperativeHistory,
    run_recursive_distributed_cooperative_filter,
)
from cooperative.topology import NetworkTopology
from interfaces.data_objects import ObservationMessage

Array = np.ndarray


@dataclass(frozen=True)
class DualTrackCooperativeHistory:
    private_history: RecursiveCooperativeHistory
    cooperative_history: RecursiveCooperativeHistory

    @property
    def timestamps(self) -> Array:
        return self.cooperative_history.timestamps

    @property
    def node_ids(self) -> list[str]:
        return self.cooperative_history.node_ids


def run_dual_track_distributed_cooperative_filter(
    *,
    timestamps: Array,
    initial_state_by_node: Mapping[str, Array],
    initial_covariance_by_node: Mapping[str, Array],
    topology: NetworkTopology,
    observation_messages: Iterable[ObservationMessage],
    process_noise_acceleration: float = 1e-4,
    cooperative_observation_usage: str = "both_endpoints",
    gate_enable: bool = False,
    gate_threshold: float = np.inf,
    gate_mode: str = "soft",
    soft_scale: float = 20.0,
) -> DualTrackCooperativeHistory:
    """Separate the outward-facing private track from cooperative feedback.

    The private track uses only observations generated by the local observer.
    The cooperative track may also consume shared copies, but all state
    messages used by that track are fixed to the private predicted histories.
    """

    messages = list(observation_messages)
    private = run_recursive_distributed_cooperative_filter(
        timestamps=timestamps,
        initial_state_by_node=initial_state_by_node,
        initial_covariance_by_node=initial_covariance_by_node,
        topology=topology,
        observation_messages=messages,
        observation_usage="observer_only",
        process_noise_acceleration=process_noise_acceleration,
        gate_enable=gate_enable,
        gate_threshold=gate_threshold,
        gate_mode=gate_mode,
        soft_scale=soft_scale,
    )
    cooperative = run_recursive_distributed_cooperative_filter(
        timestamps=timestamps,
        initial_state_by_node=initial_state_by_node,
        initial_covariance_by_node=initial_covariance_by_node,
        topology=topology,
        observation_messages=messages,
        state_channel=MessageChannel(),
        observation_channel=MessageChannel(),
        observation_usage=cooperative_observation_usage,
        process_noise_acceleration=process_noise_acceleration,
        gate_enable=gate_enable,
        gate_threshold=gate_threshold,
        gate_mode=gate_mode,
        soft_scale=soft_scale,
        broadcast_state_history_by_node=private.predicted_state_history_by_node,
        broadcast_covariance_history_by_node=(
            private.predicted_covariance_history_by_node
        ),
    )
    return DualTrackCooperativeHistory(
        private_history=private,
        cooperative_history=cooperative,
    )
